function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t228__init(recid){var el=$('#rec'+recid);var mobile=el.find('.t228__mobile');var fixedBlock=mobile.css('position')==='fixed'&&mobile.css('display')==='block';setTimeout(function(){el.on('click','.t-menusub__target-link',function(){if(isMobile){if($(this).hasClass('t-menusub__target-link_active')){el.find('.t228').trigger('overflow')}else{el.find('.t228').trigger('nooverflow')}}});el.find('.t-menu__link-item:not(.t-menusub__target-link):not(.tooltipstered):not(.t794__tm-link)').on('click',function(){if($(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
if(fixedBlock){mobile.trigger('click')}});el.find('.t-menusub__link-item').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__right_buttons_but .t-btn').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__positionabsolute');el.find('.t228').on('overflow',function(){t228_checkOverflow(recid)});el.find('.t228').on('nooverflow',function(){t228_checkNoOverflow(recid)});el.find('.t228').on('showME601a',function(){el.find('.t966__menu-link').on('click',function(){if(fixedBlock){mobile.trigger('click')}})})},500)}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){var el=$('#rec'+recid);if($(window).width()>980){var t228_navLinks=el.find(".t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){setTimeout(function(){t228_catchScroll(t228_navLinks)},500)}}}
function t228_checkOverflow(recid){var el=$('#rec'+recid);var menu=el.find('.t228');var winHeight=$(window).height();if(menu.css('position')==='fixed'){menu.addClass('t228__overflow');menu[0].style.setProperty('height',winHeight-$('.t228__mobile_container').outerHeight(!0)+'px','important')}}
function t228_checkNoOverflow(recid){var el=$('#rec'+recid);var menu=el.find('.t228');var submenus=el.find('.t966__tooltip-menu_mobile');if(menu.css('position')==='fixed'){menu.removeClass('t228__overflow');menu[0].style.setProperty('height','auto')}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=[],t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=$(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref($(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=$(this)});t228_sections.sort(function(a,b){return b.offset().top-a.offset().top});t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var clickedSection=t228_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');$(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=$(window).scrollTop();var t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!==0&&t228_clickedSectionId===null&&t228_sections[t228_sections.length-1].offset().top>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
$(t228_sections).each(function(e){var t228_curSection=$(this),t228_id=t228_curSection.attr('id'),t228_sectionTop=t228_curSection.offset().top,t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=$(document).height()-$(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setWidth(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth();if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}
el.find(".t228__centerside").removeClass("t228__centerside_hidden")}
function t228_setBg(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{el.find(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");var topoffset=el.data('top-offset');if(topoffset&&parseInt(topoffset)>0){el.animate({"opacity":"1","top":topoffset+"px"},200,function(){})}else{el.animate({"opacity":"1","top":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}}})}}
function t228_changebgopacitymenu(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var el=$("#rec"+recid);var menu=el.find(".t228");var burger=el.find(".t228__mobile");burger.on('click',function(e){menu.fadeToggle(300);burger.toggleClass("t228_opened")});$(window).bind('resize',t_throttle(function(){if($(window).width()>980){menu.fadeIn(0)}}))}
function t347_setHeight(recid){var el=$('#rec'+recid);var div=el.find(".t347__table");var height=div.width()*0.5625;div.height(height)}
window.t347showvideo=function(recid){$(document).ready(function(){var el=$('#rec'+recid);var videourl='';var youtubeid=$("#rec"+recid+" .t347__video-container").attr('data-content-popup-video-url-youtube');if(youtubeid>''){videourl='https://www.youtube.com/embed/'+youtubeid}
$("#rec"+recid+" .t347__video-container").removeClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t347__iframe\" width=\"100%\" height=\"100%\" src=\""+videourl+(videourl.indexOf('?')!==-1?'&':'?')+"autoplay=1&rel=0\" frameborder=\"0\" allowfullscreen allow=\"autoplay\"></iframe>")})}
window.t347hidevideo=function(recid){$(document).ready(function(){$("#rec"+recid+" .t347__video-container").addClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("")})}
function t431_init(recid){var tableHead=t431__escapeHTML($('#rec'+recid+' .t431 .t431__data-part1').html()||"");var tableBody=t431__escapeHTML($('#rec'+recid+' .t431 .t431__data-part2').html()||"");var tableColSize=$('#rec'+recid+' .t431 .t431__table').attr("data-table-width");var hasTargetBlank=$('#rec'+recid+' .t431 .t431__table').attr("data-target-blank");var tHead=t431_parseData(tableHead);var tBody=t431_parseData(tableBody);var colSize=t431_parseData(tableColSize);var maxColNum=t431__findMaxRowLengthInTable(tHead,tBody);var colWidth=t431__setColumnsWidth(colSize,maxColNum,recid);var container=$('#rec'+recid+' .t431 .t431__table');var html="";if(tHead){html+=t431__generateTable(tHead,"th",hasTargetBlank,colWidth,maxColNum)}
if(tBody){html+=t431__generateTable(tBody,"td",hasTargetBlank,colWidth,maxColNum)}
container.append(html)}
function t431__findMaxRowLengthInTable(arrayHead,arrayData){var headMaxLength=0;var dataMaxLength=0;if(arrayHead){headMaxLength=t431__findMaxRowLengInArray(arrayHead)}
if(arrayData){dataMaxLength=t431__findMaxRowLengInArray(arrayData)}
if(dataMaxLength>headMaxLength){return dataMaxLength}else{return headMaxLength}}
function t431__escapeHTML(string){var html=string.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ');var result="";var allowedTags="";['b','i','u','ul','li','ol','br','img','s','sub','sup','span','hr','pre','code','mark','strong','small'].forEach(function(value){allowedTags+=":not("+value+")"});var allowedAttrs=['alt','class','title','id','src','style','width','height','data-replace-key'];var fakeDOM=document.implementation.createHTMLDocument('fake');$.each($.parseHTML(html,fakeDOM)||[],function(i,$el){var el=$($el)[0];if(!$($el).is(allowedTags)){if(el.nodeType!==3&&el.nodeType!==8){var temp=document.createElement(el.tagName);allowedAttrs.forEach(function(value){if(el.getAttribute(value)!==null){temp.setAttribute(value,el.getAttribute(value).replace(/javascript:/gi,''))}});temp.textContent=el.textContent;result+=temp.outerHTML}else{result+=el.textContent}}});return result}
function t431__findMaxRowLengInArray(curArray){var maxLength=0;for(var i=0;i<curArray.length;i++){if(curArray[i].length>maxLength){maxLength=curArray[i].length}}
return maxLength}
function t431__setColumnsWidth(colWidth,colsNumber,recid){if(colWidth){return colWidth[0]}else{var tableWidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(tableWidth/colsNumber+"px")}}
function t431__generateTable(arrayValues,colTag,hasTargetBlank,colWidth,maxColNumber){var html="";var tag="";if(colTag=="td"){tag="tbody"}else{tag="thead"}
html+='<'+tag+' class="t431__'+tag+'">';for(var i=0;i<arrayValues.length;i++){if(colTag=="td"){if((i+1)%2>0){html+='<tr class="t431__oddrow">'}else{html+='<tr class="t431__evenrow">'}}else{html+='<tr>'}
var addingCols=0;if(arrayValues[i].length<maxColNumber){addingCols=maxColNumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+addingCols);j++){if(arrayValues[i][j]){var curWidth="";if(Array.isArray(colWidth)&&colWidth[j]){curWidth=colWidth[j].myText}else{curWidth=colWidth}
var ColWithAttr='';if(colTag=="td"){ColWithAttr='<td class="t431__td t-text" width="'+curWidth+'">'}else{ColWithAttr='<th class="t431__th t-title" width="'+curWidth+'">'}
if(arrayValues[i][j].myHref){var tBlank="";if(hasTargetBlank){tBlank="target=\"_blank\""}
var linkWithAttr="";var linkCloseTag="";if(arrayValues[i][j].myHrefType=="link"){linkWithAttr='<a href="'+arrayValues[i][j].myHref+'"'+tBlank+'>';linkCloseTag='</a>'}else{linkWithAttr='<div class="t431__btnwrapper"><a href="'+arrayValues[i][j].myHref+'"'+tBlank+' class="t-btn t-btn_sm"><table style="width:100%; height:100%"><tr><td>';linkCloseTag='</td></tr></table></a></div>'}
html+=ColWithAttr+linkWithAttr+arrayValues[i][j].myText+linkCloseTag+'</'+colTag+'>'}else{html+=ColWithAttr+arrayValues[i][j].myText+'</'+colTag+'>'}}else{html+='<'+colTag+' class="t431__'+colTag+'" width="'+curWidth+'">'+'</'+colTag+'>'}}
html+="</tr>"}
html+="</"+tag+">";return html}
function t431_parseData(data){if(data!==""&&typeof data!="undefined"){data=t431__addBrTag(data);var arrayTable=[];var arrayRow=[];var curItem={myText:"",myHref:"",myHrefType:""};var hasLink="";var hasLinkWithSpace="";var hasBtn="";var hasBtnWithSpace="";var endLine="";for(var i=0;i<data.length;i++){if(data[i]==";"&&!(data.slice(i-4,i)=="&lt;"||data.slice(i-4,i)=="&gt;"||data.slice(i-5,i)=="&amp;"||data.slice(i-6,i)=="&nbsp;")){arrayRow.push(curItem);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace=""}else{if(hasLink=="link="||hasLinkWithSpace==" link="||hasBtn=="button="||hasBtnWithSpace==" button="){if(curItem.myHref===""&&hasLink==="link="){curItem.myText=curItem.myText.slice(0,-5);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasLinkWithSpace===" link="){curItem.myText=curItem.myText.slice(0,-6);curItem.myHrefType="link"}else{if(curItem.myHref===""&&hasBtn==="button="){curItem.myText=curItem.myText.slice(0,-7);curItem.myHrefType="btn"}else{if(curItem.myHref===""&&hasBtnWithSpace===" button="){curItem.myText=curItem.myText.slice(0,-8);curItem.myHrefType="btn"}}}}
curItem.myHref+=(data[i])}else{curItem.myText+=(data[i]);hasLink=t431__checkSubstr("link=",hasLink,data[i]);hasLinkWithSpace=t431__checkSubstr(" link=",hasLinkWithSpace,data[i]);hasBtn=t431__checkSubstr("button=",hasBtn,data[i]);hasBtnWithSpace=t431__checkSubstr(" button=",hasBtnWithSpace,data[i])}
endLine=t431__checkSubstr("<br />",endLine,data[i]);if(endLine=="<br />"){if(curItem.myHref){curItem.myHref=curItem.myHref.slice(0,-6)}else{curItem.myText=curItem.myText.slice(0,-6)}
arrayRow.push(curItem);arrayTable.push(arrayRow);curItem={myText:"",myHref:""};hasLink="";hasLinkWithSpace="";hasBtn="";hasBtnWithSpace="";arrayRow=[]}}}
if(arrayRow.length>0||curItem.myText!==""){if(curItem!==""){arrayRow.push(curItem)}
arrayTable.push(arrayRow)}}
return arrayTable}
function t431__checkSubstr(targetSubstr,curSubstr,curSymbol){if(!curSubstr&&curSymbol==targetSubstr[0]){return curSymbol}else{if(curSubstr){for(var i=0;i<(targetSubstr.length-1);i++){if(curSubstr[curSubstr.length-1]==targetSubstr[i]&&curSymbol==targetSubstr[i+1]){return(curSubstr+=curSymbol)}}}}}
function t431__addBrTag(oldStringItem){var newStringItem="";for(var i=0;i<oldStringItem.length;i++){if(oldStringItem[i]=="\n"||oldStringItem[i]=="\r"){newStringItem+="<br />"}else{newStringItem+=oldStringItem[i]}}
return newStringItem.replace(/&nbsp;/g,' ')}
function t431_createTable(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)}
function t431__generateHtml(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+='<'+t431__theadorbodytag+' class="t431__'+t431__theadorbodytag+'">';var t431__firstbodyrowstyle="";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart}
function t486_setHeight(recid){var el=$('#rec'+recid);var window_width=$(window).width();if(window_width>980){el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').innerWidth());var textwrapper=el.find('.t486__textwrapper');var blockimg=el.find('.t486__imgcontainer');textwrapper.css('height',blockimg.innerHeight())}else{el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').width());el.find('.t486__textwrapper').css('height','auto')}}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).on('load',function(){t570_setMapHeight(recid)});$(window).on('resize',function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t608_setHeight(recid){var el=$("#rec"+recid);var image=el.find(".t608__bgimg");image.each(function(){var width=$(this).attr("data-image-width");var height=$(this).attr("data-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t668_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t668__header");var accordion=el.find('.t668__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t668__opened").next().slideUp()}
$(this).toggleClass("t668__opened");$(this).next().slideToggle();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t690_onSuccess(t690_form){var t690_inputsWrapper=t690_form.find('.t-form__inputsbox');var t690_inputsHeight=t690_inputsWrapper.height();var t690_inputsOffset=t690_inputsWrapper.offset().top;var t690_inputsBottom=t690_inputsHeight+t690_inputsOffset;var t690_targetOffset=t690_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t690_target=t690_targetOffset-200}else{var t690_target=t690_targetOffset-100}
if(t690_targetOffset>$(window).scrollTop()||($(document).height()-t690_inputsBottom)<($(window).height()-100)){t690_inputsWrapper.addClass('t690__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t690_target},400);setTimeout(function(){t690_inputsWrapper.addClass('t690__inputsbox_hidden')},400)}
var successurl=t690_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');el.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}));if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop");window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var rec=$('#rec'+recid);var popup=rec.find('.t-popup');popup.css('display','block');var $range=rec.find('.t-range');$range.trigger('popupOpened');var range=$range.get(0);if(range){var triggerChangeEvent;if(/msie|trident/.test(navigator.userAgent)){triggerChangeEvent=document.createEvent('Event');triggerChangeEvent.initEvent('popupOpened',!0,!1)}else{triggerChangeEvent=new Event('popupOpened')}
range.dispatchEvent(triggerChangeEvent)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
rec.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup(recid)}});rec.find('.t-popup__close').click(function(e){t702_closePopup(recid)});rec.find('.t-submit[href*="#"]').click(function(e){if($('body').hasClass('t-body_scroll-locked')){$('body').removeClass('t-body_scroll-locked')}});rec.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup(recid)}})}
function t702_closePopup(recid){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t720_onSuccess(t720_form){var t720_inputsWrapper=t720_form.find('.t-form__inputsbox');var t720_inputsHeight=t720_inputsWrapper.height();var t720_inputsOffset=t720_inputsWrapper.offset().top;var t720_inputsBottom=t720_inputsHeight+t720_inputsOffset;var t720_targetOffset=t720_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t720_target=t720_targetOffset-200}else{var t720_target=t720_targetOffset-100}
if(t720_targetOffset>$(window).scrollTop()||($(document).height()-t720_inputsBottom)<($(window).height()-100)){t720_inputsWrapper.addClass('t720__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t720_target},400);setTimeout(function(){t720_inputsWrapper.addClass('t720__inputsbox_hidden')},400)}
var successurl=t720_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t720_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);el.find(".t-cover__container").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t794_init(recid){var hook=$('#rec'+recid+' .t794').attr('data-tooltip-hook');if(typeof hook==="undefined"||hook===""){return}
var hookLinks=$('a[href="'+hook+'"][data-submenu-disallowed!="yes"]');hookLinks.addClass('t794__tm-link');hookLinks.attr('data-tooltip-menu-id',recid);t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var submenu=$('#rec'+recid+' .t794__tooltip-menu');var content=submenu.find('t794__content');if(window.isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
$(window).bind('scroll',t_throttle(function(){content.hover(function(){},function(){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})},300));$('.t794__tooltip-menu a[href*="#"]').click(function(){t794_hideSubmenu(submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu');$('.t794__tooltip-menu a[href*="#"]').removeClass('t-active');$(this).addClass('t-active')})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');hookLinks.on('click',function(e){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}else{var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)}
e.preventDefault()});$(document).click(function(e){var isInsideSubmenu=($(e.target).hasClass('t794__tooltip-menu')||$(e.target).parents('.t794__tooltip-menu').length>0);var isAnchor=($(e.target).hasClass('t794__tm-link')||$(e.target).parents('.t794__tm-link').length>0);if(isAnchor){var curAnchor;if($(e.target).hasClass('t794__tm-link')){curAnchor=$(e.target)}else{curAnchor=$(e.target).parents('.t794__tm-link')}
if(curAnchor.attr('data-tooltip-menu-id')!=recid&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}}
if(!isInsideSubmenu&&!isAnchor&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on('mouseover',function(){if($(this).hasClass('t794__tooltip-menu')&&!$(this).hasClass('t794__tooltip-menu_show')){return}
clearTimeout(timer);if($(this).hasClass('t794__tooltip-menu')&&submenu.hasClass('t794__tooltip-menu_show')){return}
var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)});hookLinks.add(submenu).on('mouseout',function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)});hookLinks.on('click',function(e){e.preventDefault()})}
function t794_showSubmenu(curAnchor,submenu,vIndent){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorLeft=curAnchor.offset().left;var anchorTop=curAnchor.offset().top;submenu.attr('data-pos-fixed','no');var parentMenu=curAnchor.closest('[data-menu="yes"]');var parentZeroMenu=curAnchor.closest('.t396__artboard');if(parentMenu.length&&parentMenu.css('position')==='fixed'){submenu.attr('data-pos-fixed','yes')}
var menuFixed=submenu.attr('data-pos-fixed');var submenuContent=submenu.find('.t794__content');if(typeof vIndent!='undefined'&&vIndent!=''){vIndent=vIndent.replace('px','')*1;vIndent=vIndent+10}
var posy;if(menuFixed=='yes'){posy=(anchorTop-scrollTop)+anchorHeight+vIndent;submenu.css('position','fixed');submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom');submenuContent.css('max-height','calc(100vh - '+posy+'px)')}else{posy=anchorTop+anchorHeight+vIndent;submenu.css('position','absolute');var topSpace=anchorTop-scrollTop,bottomSpace=winHeight-topSpace;if(posy+submenuHeight>scrollTop+winHeight&&topSpace>bottomSpace){posy=posy-submenuHeight-anchorHeight-vIndent*2;submenu.removeClass('t794__tooltip-menu_bottom').addClass('t794__tooltip-menu_top')}else{submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom')}}
var posx=anchorLeft;if(parentZeroMenu.hasClass('t396__artboard_scale')&&window.tn_scale_factor){posx=isFirefox?posx:posx*window.tn_scale_factor;anchorWidth=anchorWidth*window.tn_scale_factor}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=10}}else{posx=winWidth-submenuWidth-10}
submenu.css({'display':'block','left':posx,'top':posy});submenu[0].offsetHeight;submenu.addClass('t794__tooltip-menu_show');curAnchor.addClass('t794__tm-link_active')}
function t794_hideSubmenu(submenu){submenu.css({'display':'','left':'','top':''});submenu.removeClass('t794__tooltip-menu_show');$('.t794__tm-link_active').removeClass('t794__tm-link_active')}
function t794_addArrow(recid,hookLinks){var arrow=$('#rec'+recid+' .t794').attr('data-add-arrow');if(typeof arrow==='undefined'||arrow===''){return}
hookLinks.each(function(i,el){$(el).append('<div class="t794__arrow"></div>')})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$('.t794__list_item a[href="'+url+'"]').addClass('t-active');$('.t794__list_item a[href="'+url+'/"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'/"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'/"]').addClass('t-active');if(hash){$('.t794__list_item a[href="'+hash+'"]').addClass('t-active')}}
function t819_init(recid){var rec=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tab=rec.find('.t819__tab');var select=rec.find('.t819__select');var content=rec.find('.t819__content');if(curMode!='edit'&&curMode!='preview'){t819_scrollToTabs(recid)}
t819_showTabByUrl(recid,tab,content,select);t819_showTab(tab,content,recid);t819_showTabMobile(select,content,recid)}
function t819_showTab(tab,content,recid){var tabNumber;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');tab.on('click',function(e){tabNumber=$(this).attr('data-tab-number');tab.removeClass('t819__tab_active');content.removeClass('t819__content_active');$(this).addClass('t819__tab_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumber){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t819_showTabMobile(select,content,recid){var tabNumberMobile;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');select.change(function(e){tabNumberMobile=$(this).val();content.removeClass('t819__content_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumberMobile){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t819_showTabByUrl(recid,tab,content,select){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf(recid+'-');var tabIndex=curUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!=-1){tab.each(function(i){if($(tab[i]).attr('data-tab-number')==tabIndex){$(tab[i]).addClass('t819__tab_active')}});content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabIndex){$(content[i]).addClass('t819__content_active')}});select.val(tabIndex)}else{tab.first().addClass('t819__tab_active');content.first().addClass('t819__content_active')}}
function t819_scrollToTabs(recid){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');if(tabIndexNumber!=-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length)
if(+tabRec==+recid){var tabBlock=$('#rec'+tabRec).find('.t819');var targetOffset=tabBlock.offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
$('html, body').animate({scrollTop:target},400)}}}
function t819_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}