window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('t228_overflow',!0,!0);noOverflowEvent.initEvent('t228_nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('t228_overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('t228_nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile&&window.innerWidth<=980){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',(windowHeight-mobileContainerHeight)+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}
if(menuList&&menuList.classList.contains('t228__list_hidden'))menuList.classList.remove('t228__list_hidden')})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t794_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t794__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});var parentMenu=hookLinks.length?hookLinks[0].closest('[data-menu]'):null;var tooltipMenu=rec.querySelector('.t794__tooltip-menu');var isParentFixed=parentMenu&&window.getComputedStyle(parentMenu).position==='fixed';if(tooltipMenu)tooltipMenu.setAttribute('data-pos-fixed',isParentFixed?'yes':'no');t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t_onFuncLoad('t_submenublocks__highlightActiveLinks',function(){t_submenublocks__highlightActiveLinks('.t794__list_item a')});if(menu.hasAttribute('data-full-submenu-mob')&&(window.isMobile||'ontouchend' in document)){t_onFuncLoad('t_submenublocks__setFullScreenMenu',function(){t_submenublocks__setFullScreenMenu(menu)})}}
function t794_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenuBlock=rec?rec.querySelector('.t794'):null;var isArrowAppend=submenuBlock.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks=Array.prototype.slice.call(hookLinks);hookLinks.forEach(function(hookLink){var arrow=document.createElement('div');arrow.classList.add('t794__arrow');hookLink.appendChild(arrow);var isInsideZero=hookLink.closest('.tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isInsideZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t794_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t794__tooltip-menu'):null;if(!submenu)return;var menuBlock=rec?rec.querySelector('.t794'):null;var verticalIndent=menuBlock.getAttribute('data-tooltip-margin');var content=submenu.querySelector('.t794__content');var hooksAndSubmenu=hookLinks.concat(submenu);if(window.innerWidth>980&&!('ontouchend' in document)){t_onFuncLoad('t_submenublocks__addEventsDesktop',function(){t_submenublocks__addEventsDesktop(submenu,hooksAndSubmenu,verticalIndent,'.t794')})}else{t_onFuncLoad('t_submenublocks__addEventsMobile',function(){t_submenublocks__addEventsMobile(submenu,hookLinks,verticalIndent,'.t794')})}
window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){if(submenu.classList.contains('t794__tooltip-menu_show')){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')})}})}},300));var tooltipLinks=document.querySelectorAll('.t794__tooltip-menu a[href*="#"]');Array.prototype.forEach.call(tooltipLinks,function(tooltipLink){tooltipLink.addEventListener('click',function(){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')});var menuList=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(menuList,function(menu){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);menu.dispatchEvent(event)});Array.prototype.forEach.call(tooltipLinks,function(link){link.classList.remove('t-active')});tooltipLink.classList.add('t-active')})})}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href$="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var ranges=rec.querySelectorAll('.t-range');var documentBody=document.body;if(ranges.length){Array.prototype.forEach.call(ranges,function(range){t702__triggerEvent(range,'popupOpened')})}
t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook);t_onFuncLoad('t_forms__calculateInputsWidth',function(){t_forms__calculateInputsWidth(recId)})}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup):not(.t945__popup)');if(popupAll.length==1){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}}
if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t490_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t608_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t608');if(!container)return;var bgImages=rec.querySelectorAll('.t608__bgimg');for(var i=0;i<bgImages.length;i++){var bgImage=bgImages[i];var bgImageWidth=bgImage.getAttribute('data-image-width');var bgImageHeight=bgImage.getAttribute('data-image-height');var ratio=bgImageHeight/bgImageWidth;var paddingBottom=ratio*100;bgImage.style.paddingBottom=paddingBottom+'%'}}
function t486_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var textWrapper=rec.querySelector('.t486__textwrapper');if(!textWrapper)return;var images=rec.querySelectorAll('.t486__blockimg');var imageContainer=rec.querySelector('.t486__imgcontainer');var imageHeight=images[0].clientWidth;if(window.innerWidth>980){for(var i=0;i<images.length;i++){images[i].style.height=imageHeight+'px'}
textWrapper.style.height=imageContainer.clientWidth+'px'}else{var imageStyle=getComputedStyle(images[0],null);var imagePaddingLeft=parseInt(imageStyle.paddingLeft)||0;var imagePaddingRight=parseInt(imageStyle.paddingRight)||0;var imageWidth=images[0].clientWidth-(imagePaddingLeft+imagePaddingRight);for(var i=0;i<images.length;i++){images[i].style.height=imageWidth+'px'}
textWrapper.style.height='auto'}}
function t720_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t720_fixcontentheight(recId){var rec=document.getElementById('rec'+recId);var cover=rec.querySelector('.t-cover');var coverFilter=rec.querySelector('.t-cover__filter');var coverCarrier=rec.querySelector('.t-cover__carrier');var coverWrapper=rec.querySelector('.t-cover__wrapper');var coverContainer=rec.querySelector('.t-cover__container');var coverStyle=getComputedStyle(cover,null);var coverPaddingTop=parseInt(coverStyle.paddingTop)||0;var coverPaddingBottom=parseInt(coverStyle.paddingBottom)||0;var coverHeight=cover.clientHeight-(coverPaddingTop+coverPaddingBottom);var hookContent=rec.querySelector('div[data-hook-content]');var hookContentHeight=hookContent.offsetHeight;if(hookContentHeight>300&&coverHeight<hookContentHeight){var newHookContentHeight=hookContentHeight+120;if(newHookContentHeight>1000)newHookContentHeight+=100;console.log('auto correct cover height: '+newHookContentHeight);cover.style.height=newHookContentHeight+'px';if(coverFilter)coverFilter.style.height=newHookContentHeight+'px';if(coverCarrier)coverCarrier.style.height=newHookContentHeight+'px';if(coverWrapper)coverWrapper.style.height=newHookContentHeight+'px';if(coverContainer)coverContainer.style.height=newHookContentHeight+'px';if(window.isMobile===!1){setTimeout(function(){if(coverCarrier.querySelector('iframe')){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(coverCarrier,newHookContentHeight+'px')}},2000)}}}
function t668_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t668');if(!container)return;var accordion=rec.querySelectorAll('.t668__accordion')[0];var headers=rec.querySelectorAll('.t668__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var content=rec.querySelector('.t668__content');if(!content)return;var accordionScroll;var contentStyle=window.getComputedStyle(content,null);if(!contentStyle&&typeof contentStyle!=='object')return;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordionScroll='false';accordion='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t668__trigger-button');var activeHeight=0;var isAccordionDown=!1;if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded}
if(element.classList.contains('t668__opened')){element.classList.remove('t668__opened');t668_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t668__getOldAction(rec);isAccordionDown=t668__getAccordionPosition(headers,element)}
if(accordion==='true'){t668_accordionAllHide(headers)}
element.classList.add('t668__opened');container.style.display='block';var paddingBottom=Number(contentStyle.paddingBottom.replace('px',''));var height=container.scrollHeight+paddingBottom;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t668__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t668_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t668__opened');t668_accordionHide(elementHide.nextElementSibling)}}
function t668_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight=0},0)}
function t668__getOldAction(rec){var activeHeader=rec.querySelector('.t668__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t668__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t668__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t668__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t668__scroll(target)}}
function t668__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t668__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t668__animateScroll(){currentTime+=increment;window.scrollTo(0,t668__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t668__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t668__animateScroll()}
function t819_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');var tabs=rec.querySelectorAll('.t819__tab');var select=rec.querySelector('.t819__select');var content=rec.querySelectorAll('.t819__content');if(!tabs.length)return;if(!content.length)return;if(currentMode!=='edit'&&currentMode!=='preview'){t819_scrollToTabs(recid);window.onload=function(){t819_scrollToTabs(recid)}}
t819_showTabByUrl(recid,tabs,content,select);t819_showTab(recid,tabs,content,currentMode);t819_showTabMobile(recid,select,content,currentMode)}
function t819_showTab(recid,tabs,content,currentMode){var rec=document.querySelector('#rec'+recid);if(!rec)return;Array.prototype.forEach.call(tabs,function(tabItem){tabItem.addEventListener('click',function(event){var tabNumber=this.getAttribute('data-tab-number');rec.querySelector('.t819__wrapper').setAttribute('data-tab-current',tabNumber);Array.prototype.forEach.call(tabs,function(tabItem){tabItem.classList.remove('t819__tab_active');var button=tabItem.querySelector('.t817__tab-name');if(button){button.setAttribute('tabindex',-1);button.setAttribute('aria-selected',!1)}});Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t819__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumber,10)){contentItem.classList.add('t819__content_active')}});tabItem.classList.add('t819__tab_active');var currentButton=tabItem.querySelector('.t817__tab-name');if(currentButton){currentButton.setAttribute('tabindex',0);currentButton.setAttribute('aria-selected',!0)}
t819_changeUrl(recid,currentMode,tabNumber);t819__updateLazyLoad(currentMode);event.preventDefault()});tabItem.addEventListener('keydown',function(event){var currentIndex=Number(rec.querySelector('.t819__wrapper').getAttribute('data-tab-current'));var prevent=!1;switch(event.key){case 'Left':case 'ArrowLeft':currentIndex=currentIndex===1?tabs.length:currentIndex-1;t819_showActiveTabFromKeyboard(recid,tabs,content,currentMode,currentIndex);prevent=!0;break;case 'Right':case 'ArrowRight':currentIndex=currentIndex===tabs.length?1:currentIndex+1;t819_showActiveTabFromKeyboard(recid,tabs,content,currentMode,currentIndex);prevent=!0;break;default:break}
if(prevent){event.stopPropagation();event.preventDefault()}})})}
function t819_showActiveTabFromKeyboard(recid,tabs,content,currentMode,currentIndex){var rec=document.querySelector('#rec'+recid);Array.prototype.forEach.call(tabs,function(tabItem){tabItem.classList.remove('t819__tab_active');var button=tabItem.querySelector('.t819__tab-name');if(button){button.setAttribute('tabindex',-1);button.setAttribute('aria-selected',!1)}});Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t819__content_active')});var currentTab=rec.querySelector('[data-tab-number="'+currentIndex+'"]');if(!currentTab)return;currentTab.classList.add('t819__tab_active');var currentButton=currentTab.querySelector('.t819__tab-name');if(currentButton){currentButton.setAttribute('tabindex',0);currentButton.setAttribute('aria-selected',!0);currentButton.focus()}
var currentContent=rec.querySelector('[data-tab-content-number="'+currentIndex+'"]');if(currentContent)currentContent.classList.add('t819__content_active');var tabList=rec.querySelector('.t819__wrapper');if(tabList)tabList.setAttribute('data-tab-current',currentIndex);t819_changeUrl(recid,currentMode,currentIndex);t819__updateLazyLoad(currentMode)}
function t819_changeUrl(recid,currentMode,index){t819_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+index)}}}
function t819__updateLazyLoad(currentMode){if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}}
function t819_showTabMobile(recid,select,content,currentMode){select.addEventListener('change',function(event){var tabNumberMobile=this.value;Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t819__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumberMobile,10)){contentItem.classList.add('t819__content_active')}});t819_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})}
function t819_showTabByUrl(recid,tabs,content,select){var rec=document.querySelector('#rec'+recid);var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf(recid+'-');var tabIndex=currentUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!==-1){Array.prototype.forEach.call(tabs,function(tabItem){if(parseInt(tabItem.getAttribute('data-tab-number'),10)===parseInt(tabIndex,10)){tabItem.classList.add('t819__tab_active');tabItem.querySelector('.t819__tab-name').setAttribute('tabindex',0);tabItem.querySelector('.t819__tab-name').setAttribute('aria-selected',!0)}});Array.prototype.forEach.call(content,function(contentItem){if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabIndex,10)){contentItem.classList.add('t819__content_active')}});select.value=tabIndex;rec.querySelector('.t819__wrapper').setAttribute('data-tab-current',tabIndex)}else{tabs[0].classList.add('t819__tab_active');content[0].classList.add('t819__content_active');rec.querySelector('.t819__wrapper').setAttribute('data-tab-current',1);tabs[0].querySelector('.t819__tab-name').setAttribute('tabindex',0);tabs[0].querySelector('.t819__tab-name').setAttribute('aria-selected',!0)}}
function t819_scrollToTabs(recid){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf('#!/tab/');var tabIndexNumberStart=currentUrl.indexOf('tab/');if(parseInt(tabIndexNumber,10)!==-1){var tabRecord=currentUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(parseInt(tabRecord,10)===parseInt(recid,10)){var tabBlock=document.querySelector('#rec'+tabRecord).querySelector('.t819');var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;if(window.innerWidth>960){var target=targetOffset-200}else{var target=targetOffset-100}
t819_scrollToEl(target,300)}}}
function t819_removeUrl(){var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tab/')}
currentUrl=currentUrl.substring(0,indexToRemove);if(parseInt(indexToRemove,10)!==-1){if(typeof history.replaceState==='function'){window.history.replaceState('','',currentUrl)}}}
function t819_scrollToEl(elTopPos,duration){if(elTopPos===window.pageYOffset)return!1;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(10*(elTopPos||window.pageYOffset))/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}else if(cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t347_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var table=rec?rec.querySelector('.t347__table'):null;var tableWidth=table?table.offsetWidth:0;var tableHeight=tableWidth*0.5625;if(table)table.style.height=tableHeight+'px'}
function t347showvideo(recid){if(document.readyState!=='loading'){t347_createVideo(recid)}else{document.addEventListener('DOMContentLoaded',function(){t347_createVideo(recid)})}}
function t347_createVideo(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoContainer=rec.querySelector('.t347__video-container');var videoCarrier=rec.querySelector('.t347__video-carier');if(videoContainer.querySelector('.t347__video'))return;if(videoContainer)videoContainer.classList.remove('t347__hidden');if(!videoContainer.classList.contains('t347__html5video')&&!videoContainer.classList.contains('t347__vimeovideo')){var youTubeURL=videoContainer?videoContainer.getAttribute('data-content-popup-video-url-youtube'):'';var videoURL=youTubeURL?'https://www.youtube.com/embed/'+youTubeURL:'';videoCarrier.insertAdjacentHTML('beforeend','<iframe id="youtubeiframe'+recid+'" class="t347__iframe t347__video" width="100%" height="100%" src="'+videoURL+(videoURL.indexOf('?')!==-1?'&':'?')+'autoplay=1&rel=0" frameborder="0" allowfullscreen allow="autoplay"></iframe>')}
var videoWrapper=rec.querySelector('.t347__table');var computedHeight=window.getComputedStyle(videoWrapper).height;if(videoContainer.classList.contains('t347__html5video')){var videoSource=videoContainer.getAttribute('data-videomp4-url');if(!videoSource)return;videoCarrier.insertAdjacentHTML('beforeend','<video width="100%" autoplay controls class="t347__video">'+'<source src="'+videoSource+'" type="video/mp4">'+'Your browser does not support the video tag'+'</video>');var HTMLVideoHeight=videoCarrier.getAttribute('data-height');videoCarrier.height=HTMLVideoHeight?parseInt(HTMLVideoHeight,10):parseInt(computedHeight,10);var createdVideo=videoContainer.querySelector('.t347__video');createdVideo.focus()}
if(videoContainer.classList.contains('t347__vimeovideo')){var videoSource=videoContainer.getAttribute('data-vimeo-url');var vimeoSourceHash=videoContainer.getAttribute('data-vimeo-hash');if(!videoSource)return;var vimeoCurrentSourse=vimeoSourceHash?videoSource+'?h='+vimeoSourceHash+'&autoplay=1':videoSource+'?autoplay=1';videoCarrier.insertAdjacentHTML('beforeend','<iframe '+'src="https://player.vimeo.com/video/'+vimeoCurrentSourse.trim()+'" '+'frameborder="0" '+'allow="autoplay; fullscreen; picture-in-picture" '+'allowfullscreen '+'class="t347__video" '+'style="width: 100%; height: 100%;"> '+'</iframe>');var vimeoVideoHeight=videoCarrier.getAttribute('data-height');videoCarrier.style.height=vimeoVideoHeight?vimeoVideoHeight:computedHeight;var createdVideo=videoContainer.querySelector('.t347__video');createdVideo.focus()}}